# Generated by Django 5.0.6 on 2024-12-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_image_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='anonymity',
            field=models.BooleanField(default='False'),
        ),
    ]
