# Generated by Django 5.0.6 on 2024-12-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_comment_anonymity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anonymity',
            field=models.BooleanField(default='False'),
        ),
    ]
